In [1]:
import pandas as pd 

csv = '../data/cleaned/cleaned_combined_dataset_gpw3.csv'

df = pd.read_csv(csv)

In [2]:
df.head()

,city_boundary_specification_(lau/grid),country_or_territory,city,total_city_population_*,year,air_pollutant,health_risk_scenario,populated_area_[km2],air_pollution_average_[ug/m3],air_pollution_population_weighted_average_[ug/m3],premature_deaths,premature_deaths_-_lower_ci,premature_deaths_-_upper_ci,years_of_life_lost,years_of_life_lost_-_lower_ci,years_of_life_lost_-_upper_ci,remature_deaths_-_upper_ci
0,Urban Centres (grid),Austria,All Urban Centres in a Country,2405646,2005,NO2,WHO_2005_HRAPIE_Scen_Base,446,30.3,32.8,1352.0,783.0,1911.0,14704.0,8522.0,20791.0,1911.0
1,Urban Centres (grid),Belgium,All Urban Centres in a Country,3030639,2005,NO2,WHO_2005_HRAPIE_Scen_Base,745,32.4,35.1,2141.0,1247.0,3017.0,22939.0,13338.0,32327.0,3017.0
2,Urban Centres (grid),Bulgaria,All Urban Centres in a Country,3010927,2005,NO2,WHO_2005_HRAPIE_Scen_Base,384,23.3,24.9,1236.0,712.0,1759.0,13367.0,7713.0,18982.0,1759.0
3,Urban Centres (grid),Cyprus,All Urban Centres in a Country,418267,2005,NO2,WHO_2005_HRAPIE_Scen_Base,131,20.3,21.0,24.0,13.0,34.0,249.0,143.0,357.0,34.0
4,Urban Centres (grid),Czechia,All Urban Centres in a Country,2464143,2005,NO2,WHO_2005_HRAPIE_Scen_Base,536,26.4,27.6,961.0,554.0,1364.0,10585.0,6105.0,15045.0,1364.0

In [ ]:
import seaborn as sns 
import numpy as np